server:
  port: 9000
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /hong
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: ad-sponsor
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: ad-search
      strip-profix: false
      #127.0.0.1:9000/hong/ad-search/fetchAds
    binlog-kafka:
      path: /ad-binlog-kafka/**
      serviceId: ad-binlog-kafka
      strip-profix: false